// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: teerhqmzhbeqowkzrdgw

class SupabaseConfig {
  static const String supabaseUrl = 'https://teerhqmzhbeqowkzrdgw.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlZXJocW16aGJlcW93a3pyZGd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzMjY5MDQsImV4cCI6MjA3NzkwMjkwNH0.6XWh4GLbMBtBuqmTfKZwktImu7OE5lQgPOzvFOp68D8';
}
